name: Generate bin file

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup npm
        run: |
          npm i
          npm install -g typescript
          cd src/scripts
      - name: Make output directory
        run: mkdir output
      - name: Show path
        run: pwd
      - name: Generate bin
        run: npm run TerrainMapGenerator.ts
      - uses: actions/upload-artifact@v4
        with:
          path: output/map.bin
