name: Generate bin file

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup npm
        run: npm i
      - name: install typescript
        run: npm install -g typescript
      - name: ls
        run: ls
      - name: Go to correct directory
        run: cd src
      - name: ls
        run: ls
      - name: go to scripts
        run: cd scripts
      - name: Make output directory
        run: mkdir output
      - name: ls
        run: ls
      - name: Show path
        run: pwd
      - name: Generate bin
        run: npm run TerrainMapGenerator.ts
      - uses: actions/upload-artifact@v4
        with:
          path: output/map.bin
